# -*- coding: utf-8 -*-
"""Pairwise Sequence Alignment (Needleman-Wunsch)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KB3_u9exzjZR9JeRA67daNGgp8LWhXYx

Pairwise Sequence Alignment (Needleman-Wunsch)
"""

from Bio import pairwise2
from Bio.pairwise2 import format_alignment

# Read sequences from a FASTA file
def read_fasta(file_path):
    with open(file_path, "r") as file:
        lines = file.readlines()
        seq1, seq2 = lines[1].strip(), lines[3].strip()  # Assumes two sequences
        return seq1, seq2

# Perform global alignment
file_path = "sequences.fasta"  # Replace with your FASTA file
seq1, seq2 = read_fasta(file_path)
alignments = pairwise2.align.globalxx(seq1, seq2)

# Print best alignment
print(format_alignment(*alignments[0]))