# -*- coding: utf-8 -*-
"""Running a BLAST Search using Biopython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Je1xmDU2pQFPmaNyQGwlPSfyW98Bz1O1
"""

from Bio.Blast import NCBIWWW, NCBIXML

# Input protein sequence
query_seq = ">seq1\nMVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPH"

# Run BLASTp
result_handle = NCBIWWW.qblast("blastp", "nr", query_seq)

# Parse and display BLAST results
blast_record = NCBIXML.read(result_handle)
for alignment in blast_record.alignments[:5]:
    print(f"Hit: {alignment.title}\nScore: {alignment.hsps[0].score}\n")